[package]
name = "blogr"
version = "0.1.0"
authors = ["Andrew Prindle <prindle.andrew@gmail.com>"]

[dependencies]
rocket-simpleauth = {path = "auth-rs"}
# chrono = "0.4.0"
# lazy_static = "0.2.8"
# multipart = "0.13.3"
# regex = "0.2"
rocket = "0.3.2"
rocket_codegen = "0.3.2"
# rocket-simpleauth = "0.3.0"
# serde_json = "1.0.2"
# serde = "1.0.11"
# serde_derive = "1.0.11"
time = "0.1"
