[global]
workers = 8


# /etc/letsencrypt/live/vishus.net/
# cert.pem
# chain.pem
# fullchain.pem
# privkey.pem
# README

[development]
address = "localhost"
port = 8000
log = "normal"
# log = "debug"
secret_key = "XJyPFUxIUU3QIozfkk/MWyAJwPb3DihykXcEiqOMfVA="
limits = { forms = 32768 }
tls = { certs = "/etc/letsencrypt/live/vishus.net/cert.pem", key = "/etc/letsencrypt/live/vishus.net/privkey.pem" }


[staging]
address = "localhost"
port = 8000
log = "debug"
secret_key = "XJyPFUxIUU3QIozfkk/MWyAJwPb3DihykXcEiqOMfVA="
limits = { forms = 32768 }

[production]
address = "localhost"
port = 8000
log = "critical"
secret_key = "XJyPFUxIUU3QIozfkk/MWyAJwPb3DihykXcEiqOMfVA="
limits = { forms = 32768 }

