[development]
address = "localhost"
port = 8000
workers = 8
log = "normal"
# log = "debug"
# secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 8000
workers = 8
log = "debug"
# secret_key = [randomly generated at launch]
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

[production]
address = "localhost"
port = 8000
workers = 8
log = "critical"
# secret_key = [randomly generated at launch]
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

